---
title: "R Notebook"
output: html_notebook
---

```{r include=FALSE}
library(tidyverse)
ggplot2::theme_set(theme_classic())
```

# initial tests and dev

```{r}
hwm <- 365
delta_x <- 0.1

xs <- read_csv("data/xs_geom/xs_b.csv") %>% 
  arrange(station_left_bank_ft) %>%
  complete(station_left_bank_ft = seq(from = min(station_left_bank_ft), to = max(station_left_bank_ft), by = delta_x)) %>%
  mutate(gse = zoo::na.approx(elevation_ngvd29_ft, x = station_left_bank_ft)) %>% 
  mutate(wse = case_when(hwm >= gse ~ hwm))

xs %>% ggplot(aes(x = station_left_bank_ft)) + 
  geom_line(aes(y = gse)) + 
  geom_line(aes(y = wse))
```

```{r}
xs %>% 
  mutate(delta_z = lag(gse, 1) - gse) %>%
  filter(!is.na(wse)) %>% 
  summarize(cross_sectional_area = hwm * (max(station_left_bank_ft) - min(station_left_bank_ft))
                                   - sum(delta_x * zoo::rollapply(gse, 2, mean)),
            wetted_perimeter = sum(sqrt(delta_x^2 + delta_z^2)),
            hydraulic_radius = cross_sectional_area / wetted_perimeter,
            )
```
# as functions

```{r}

prep_xs <- function(data, sta, elev, delta_x) {
  data %>%
    arrange({{sta}}) %>%
    mutate(sta = {{sta}}) %>%
    complete(sta = seq(from = min({{sta}}), to = max({{sta}}), by = delta_x)) %>%
    mutate(gse = zoo::na.approx({{elev}}, x = sta)) %>% 
    select(c(sta, gse))
}

calc_xs <- function(data, water_elev) {
  data %>% 
    mutate(wse = case_when(water_elev >= gse ~ water_elev)) %>%
    mutate(delta_x = abs(lag(sta, 1) - sta),
           delta_z = abs(lag(gse, 1) - gse),
           depth = wse - gse, 
           hyp_length = sqrt(delta_x^2 + delta_z^2)
           ) %>%
    filter(!is.na(wse)) %>% 
    summarize(thalweg_elevation = min(gse),
              water_surface_elevation = water_elev,
              max_depth = water_surface_elevation - thalweg_elevation,
              cross_sectional_area = sum(delta_x * depth),
              wetted_perimeter = sum(hyp_length),
              hydraulic_radius = cross_sectional_area / wetted_perimeter,
              )
  # can we convert to named list?
}

apply_water_elev_to_xs <- function(water_elev, xs) {
  calc_xs(xs, water_elev)
}

```

```{r}
xs_b <- read_csv("data/xs_geom/xs_b.csv") %>%
  prep_xs(sta = station_left_bank_ft, elev = elevation_ngvd29_ft, delta_x = 0.1)

xs_b %>% calc_xs(water_elev = 365)

# example to generate a rating curve
water_elevs <- 352:370
rating_curve <- water_elevs %>% map_df(apply_water_elev_to_xs, xs = xs_b)
rating_curve %>% ggplot(aes(x = max_depth, y = hydraulic_radius)) + geom_line()

```
```{r}

# example to calculate based on lists of water elevs
elevs <- tribble(
  ~note, ~hwm,
  "test1", 360,
  "test2", 365
) 
elevs %>% 
  pull(hwm) %>% 
  map_df(apply_water_elev_to_xs, xs = xs_b) %>% 
  left_join(elevs, by = join_by(water_surface_elevation == hwm))

```
```{r}
xs_b <- read_csv("data/xs_geom/xs_b.csv") %>%
  prep_xs(sta = station_left_bank_ft, elev = elevation_ngvd29_ft, delta_x = 0.1) %>%
  mutate(cross_section = "B")

xs_d <- read_csv("data/xs_geom/xs_d.csv") %>%
  prep_xs(sta = station_left_bank_ft, elev = elevation_ngvd29_ft, delta_x = 0.1) %>%
  mutate(cross_section = "D")

xs_e <- read_csv("data/xs_geom/xs_e.csv") %>%
  prep_xs(sta = station_left_bank_ft, elev = elevation_ngvd29_ft, delta_x = 0.1) %>%
  mutate(cross_section = "E")

xs_f <- read_csv("data/xs_geom/xs_f.csv") %>%
  prep_xs(sta = station_left_bank_ft, elev = elevation_ngvd29_ft, delta_x = 0.1) %>%
  mutate(cross_section = "F")

xs_g <- read_csv("data/xs_geom/xs_g.csv") %>%
  prep_xs(sta = station_left_bank_ft, elev = elevation_ngvd29_ft, delta_x = 0.1) %>%
  mutate(cross_section = "G")

xs_h <- read_csv("data/xs_geom/xs_h.csv") %>%
  prep_xs(sta = station_left_bank_ft, elev = elevation_ngvd29_ft, delta_x = 0.1) %>%
  mutate(cross_section = "H")

xs <- bind_rows(xs_b, xs_d, xs_e, xs_f, xs_g, xs_h)

xs %>% 
  group_by(cross_section) %>%

```


```{r}
hwm_hydraulics <- read_csv("data/high_water_marks_v2.csv") %>%
  janitor::clean_names()
hwm_hydraulics
```
